ALTER TABLE profiles
DROP COLUMN IF EXISTS document_id;

ALTER TABLE profiles
    ADD COLUMN IF NOT EXISTS bio VARCHAR(500);

ALTER TABLE players
DROP COLUMN IF EXISTS bio;

ALTER TABLE players
    ADD COLUMN IF NOT EXISTS goals INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS assists INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS matches_played INTEGER NOT NULL DEFAULT 0;
